// One camera initializer. Light measurement and image processing use only the scanner ROI.
(function(){
'use strict';
const $=id=>document.getElementById(id),wait=ms=>new Promise(r=>setTimeout(r,ms));
let cameraSession=0;
function status(text,loading=false){if($('status-text'))$('status-text').textContent=text;if($('spinner'))$('spinner').style.display=loading?'block':'none';}
function clearCapture(){window.resetUniversalCapture?.();try{beratTerbaca=0;beratTeksTerbaca='';}catch(_){}const p=$('capture-preview');if(p){p.hidden=true;p.style.display='none';p.getContext('2d')?.clearRect(0,0,p.width,p.height);}['ai-result','btn-lanjut','btn-manual','btn-retake-v19'].forEach(id=>{if($(id))$(id).style.display='none';});$('camera-ui')?.querySelector('.scanner-actions')?.classList.remove('success-v19');}
function stop(){try{window.localScanner?.stop();window.localScanner=null;localScanner=null;}catch(_){}try{window.streamKamera?.getTracks().forEach(t=>t.stop());window.streamKamera=null;streamKamera=null;}catch(_){}const v=$('kamera-video');if(v){try{v.pause();}catch(_){}v.srcObject=null;}}
function timeout(p,ms){return Promise.race([p,new Promise((_,reject)=>setTimeout(()=>reject(new Error('camera-timeout')),ms))]);}
async function openStream(){let error;for(const c of [{video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}},audio:false},{video:{facingMode:'environment'},audio:false},{video:true,audio:false}]){try{return await timeout(navigator.mediaDevices.getUserMedia(c),9000);}catch(e){error=e;}}throw error||new Error('camera-unavailable');}
function captureFrame(scanner){if(typeof scanner?.drawCrop!=='function')return null;const c=document.createElement('canvas');c.width=320;c.height=128;return scanner.drawCrop(c,320,128)?c:null;}
// Restrict detection to a BRIGHT cyan LCD, not green reflections on the scale body.
// Ignore the top/bottom scanner frame. Do not invent a rectangle if detection is uncertain.
function lcdRegion(canvas){if(!canvas)return null;const w=canvas.width,h=canvas.height,d=canvas.getContext('2d',{willReadFrequently:true}).getImageData(0,0,w,h).data,cols=new Uint16Array(w),rows=new Uint16Array(h);let found=0;
for(let y=Math.round(h*.11);y<Math.floor(h*.96);y+=2)for(let x=Math.round(w*.05);x<Math.floor(w*.98);x+=2){const i=(y*w+x)*4,r=d[i],g=d[i+1],b=d[i+2];if(r>85&&g>170&&b>170&&g>r*1.10&&b>r*1.10){cols[x]++;rows[y]++;found++;}}
if(found<100)return null;const xs=[],ys=[];for(let x=0;x<w;x+=2)if(cols[x]>=Math.max(3,h*.04))xs.push(x);for(let y=0;y<h;y+=2)if(rows[y]>=Math.max(3,w*.04))ys.push(y);
if(xs.length<18||ys.length<10)return null;const left=Math.max(0,xs[0]-4),right=Math.min(w,xs[xs.length-1]+5),top=Math.max(0,ys[0]-4),bottom=Math.min(h,ys[ys.length-1]+5);if((right-left)*(bottom-top)<w*h*.065||right-left>w*.90)return null;return {left,right,top,bottom};}
function lightOfLCD(canvas){const box=lcdRegion(canvas);if(!box)return null;const w=canvas.width,d=canvas.getContext('2d',{willReadFrequently:true}).getImageData(0,0,w,canvas.height).data;let n=0,clipped=0,near=0,min=255,max=0;for(let y=box.top;y<box.bottom;y+=2)for(let x=box.left;x<box.right;x+=2){const i=(y*w+x)*4,r=d[i],g=d[i+1],b=d[i+2],v=.299*r+.587*g+.114*b;n++;min=Math.min(min,v);max=Math.max(max,v);if(g>=250||b>=250)clipped++;if(v>232)near++;}return n?{clipped:clipped/n,near:near/n,contrast:max-min}:null;}
function snap(v,range){let n=Math.max(range.min,Math.min(range.max,v));if(Number(range.step)>0)n=range.min+Math.round((n-range.min)/range.step)*range.step;return Math.max(range.min,Math.min(range.max,n));}
async function tune(track,scanner,token){try{const range=track?.getCapabilities?.()?.exposureCompensation;if(!range||!Number.isFinite(range.min)||!Number.isFinite(range.max)||range.max<=range.min)return;let light=lightOfLCD(captureFrame(scanner));if(!light||token!==cameraSession||light.clipped<.12&&light.near<.35)return;status('Menyesuaikan cahaya layar…',true);let current=Number(track.getSettings?.().exposureCompensation);if(!Number.isFinite(current))current=0;
for(let i=0;i<2&&token===cameraSession;i++){const goal=snap(current-(i?0.45:0.75),range);if(goal>=current-.02)break;await track.applyConstraints({advanced:[{exposureCompensation:goal}]});await wait(220);const next=lightOfLCD(captureFrame(scanner));if(!next)break;current=goal;if(next.clipped<.08&&next.near<.27)break;if(next.contrast<light.contrast*.65&&next.clipped>=light.clipped)break;light=next;}}
catch(e){console.info('LCD exposure control unavailable:',e?.message||e);}}
// Fast local mean threshold on the RED channel: cyan digits are dark in red even
// when the green/blue backlight is near saturation. This does not call an OCR model.
function digitMask(source,rect,target){const sw=rect.sw,sh=rect.sh,outW=600,outH=Math.max(140,Math.round(outW*sh/sw)),pad=20,tmp=document.createElement('canvas');tmp.width=outW;tmp.height=outH;const tx=tmp.getContext('2d',{willReadFrequently:true});tx.drawImage(source,rect.sx,rect.sy,sw,sh,0,0,outW,outH);const rgba=tx.getImageData(0,0,outW,outH).data,stride=outW+1,integral=new Float64Array(stride*(outH+1));
for(let y=1;y<=outH;y++){let row=0;for(let x=1;x<=outW;x++){row+=rgba[((y-1)*outW+x-1)*4];integral[y*stride+x]=integral[(y-1)*stride+x]+row;}}
target.width=outW+pad*2;target.height=outH+pad*2;const ctx=target.getContext('2d',{willReadFrequently:true});ctx.fillStyle='#fff';ctx.fillRect(0,0,target.width,target.height);const result=ctx.createImageData(outW,outH);const radius=20;
for(let y=0;y<outH;y++){const y0=Math.max(0,y-radius),y1=Math.min(outH,y+radius+1);for(let x=0;x<outW;x++){const x0=Math.max(0,x-radius),x1=Math.min(outW,x+radius+1),mean=(integral[y1*stride+x1]-integral[y0*stride+x1]-integral[y1*stride+x0]+integral[y0*stride+x0])/((x1-x0)*(y1-y0));const v=rgba[(y*outW+x)*4]<mean-12?0:255,i=(y*outW+x)*4;result.data[i]=result.data[i+1]=result.data[i+2]=v;result.data[i+3]=255;}}
ctx.putImageData(result,pad,pad);}
// Preserve ordinary black-and-white scale readings; LCD preprocessing is opt-in
// only if cyan LCD boundary is positively detected inside the scanner box.
function installCrop(scanner){const original=scanner.drawCrop.bind(scanner);scanner.drawCrop=function(target,w,h){const source=document.createElement('canvas');source.width=w;source.height=h;if(!original(source,w,h))return false;const sample=document.createElement('canvas');sample.width=320;sample.height=128;sample.getContext('2d').drawImage(source,0,0,320,128);const roi=lcdRegion(sample);if(!roi){target.width=w;target.height=h;target.getContext('2d').drawImage(source,0,0);return true;}
const sx=roi.left/320*w,sy=roi.top/128*h,lw=(roi.right-roi.left)/320*w,lh=(roi.bottom-roi.top)/128*h;
// Exclude LOCK label above and Kg below; keep all 4 digits and decimal point.
const rect={sx:sx+lw*.045,sy:sy+lh*.18,sw:lw*.935,sh:lh*.70};digitMask(source,rect,target);return true;};}
function enableCapture(retry=false,track=null,scanner=null,token=0){const btn=$('btn-capture');if(!btn)return;btn.style.display='block';btn.disabled=false;btn.style.opacity='1';btn.style.pointerEvents='auto';btn.textContent=retry?'↻ Coba Kamera Lagi':'📸 Ambil Gambar';btn.onclick=retry?()=>window.mulaiKamera(window.jenisSampahAktif||'Sampah'):async()=>{if(btn.disabled)return;btn.disabled=true;try{if(track&&scanner)await tune(track,scanner,token);if(token===cameraSession)await window.ambilGambarTimbangan?.();}finally{btn.disabled=false;}};if(!retry)window.warmUniversalOCR?.();}
function install(){window.mulaiKamera=async function(name){const token=++cameraSession;window.tutupModalPaksa?.();window.jenisSampahAktif=name;try{jenisSampahAktif=name;}catch(_){}clearCapture();stop();const ui=$('camera-ui');if(ui)ui.style.display='block';const btn=$('btn-capture');if(btn){btn.style.display='block';btn.disabled=true;btn.style.opacity='.55';btn.textContent='📷 Menyiapkan Kamera…';}status('Menyiapkan kamera…',true);if(!navigator.mediaDevices?.getUserMedia){status('Browser tidak mendukung kamera. Gunakan input manual.');if($('btn-manual'))$('btn-manual').style.display='block';enableCapture(true);return;}
try{const stream=await openStream();if(token!==cameraSession){stream.getTracks().forEach(t=>t.stop());return;}window.streamKamera=stream;try{streamKamera=stream;}catch(_){}const video=$('kamera-video');video.muted=true;video.playsInline=true;video.srcObject=stream;await timeout(video.play(),5000);const started=Date.now();while(!video.videoWidth&&Date.now()-started<5000)await wait(100);if(!video.videoWidth)throw new Error('video-no-frame');const track=stream.getVideoTracks()[0],caps=track.getCapabilities?.()||{};try{if(caps.focusMode?.includes?.('continuous'))await track.applyConstraints({advanced:[{focusMode:'continuous'}]});}catch(_){}if($('btn-torch'))$('btn-torch').style.display='none';if(typeof window.ScaleLocalScanner==='function'){const scanner=new window.ScaleLocalScanner({video,scannerBox:$('scanner-box'),workCanvas:$('canvas-local'),onStatus:()=>{},onFallback:()=>{},onReading:()=>{}});window.localScanner=scanner;try{localScanner=scanner;}catch(_){}await wait(200);await tune(track,scanner,token);if(token!==cameraSession)return;scanner.stop();installCrop(scanner);enableCapture(false,track,{drawCrop:scanner.drawCrop},token);}else enableCapture();status('Kamera siap. Arahkan angka lalu tekan Ambil Gambar.');}
catch(error){console.error('Camera initialization failed:',error);stop();status(error?.name==='NotAllowedError'?'Izin kamera ditolak. Aktifkan izin kamera.':'Kamera tidak dapat dibuka. Coba lagi atau input manual.');if($('btn-manual'))$('btn-manual').style.display='block';enableCapture(true);}};}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();window.addEventListener('load',()=>setTimeout(install,0),{once:true});
})();