// Home UI v25: nav-free home/profile/modal styling.
(function(){
  'use strict';
  const $=id=>document.getElementById(id);

  function installStyle(){
    if($('ui-home-v25-style'))return;
    const s=document.createElement('style');s.id='ui-home-v25-style';s.textContent=`
      :root{--mint-bg:#ecfaf6;--mint-soft:#dff6ef;--mint-card:#b8efe0;--green:#16b98a;--green-dark:#087458;--ink:#163c32;--muted:#70847d;--line:#d7ece5;--white:#fff}
      *{box-sizing:border-box}html,body{min-height:100%;background:var(--mint-bg)!important;background-image:none!important}body{margin:0!important;color:var(--ink)!important;font-family:'Segoe UI',Tahoma,Geneva,Verdana,sans-serif!important;display:flex!important;justify-content:center!important;align-items:flex-start!important;overflow-x:hidden!important}body::before,body::after{content:none!important;display:none!important}
      #form-login{width:min(92vw,390px)!important;max-width:390px!important;margin:8vh auto 40px!important;padding:28px 24px 24px!important;border:1px solid var(--line)!important;border-radius:28px!important;background:#fff!important;box-shadow:0 18px 50px rgba(32,103,81,.10)!important;color:var(--ink)!important;position:relative!important;z-index:5!important}
      #form-login::before{content:'♻️';width:74px;height:74px;border-radius:24px;display:flex;align-items:center;justify-content:center;margin:0 auto 16px;background:linear-gradient(145deg,#d9f8ef,#bdeedc);font-size:34px;box-shadow:0 10px 24px rgba(22,185,138,.14)}
      #form-login h2{margin:0 0 7px!important;text-align:center!important;color:var(--ink)!important;font-size:23px!important}#form-login h2::after{content:'Atur profil sebelum mulai mencatat setoran sampah';display:block;margin-top:7px;font-size:12px;font-weight:500;color:var(--muted)}
      #form-login label{color:var(--ink)!important;text-shadow:none!important;font-size:12px!important;font-weight:750!important}#form-login input{width:100%!important;padding:13px 14px!important;border:1px solid var(--line)!important;border-radius:15px!important;background:#f8fffc!important;color:var(--ink)!important;outline:none!important}.btn-submit{background:var(--green)!important;color:#fff!important;border-radius:16px!important}
      #dropdown-list{border:1px solid var(--line)!important;border-radius:15px!important;box-shadow:0 14px 34px rgba(26,84,66,.14)!important;overflow:hidden!important}
      #halaman-beranda{width:100%!important;max-width:430px!important;min-height:100vh!important;height:auto!important;padding:20px 18px calc(92px + env(safe-area-inset-bottom))!important;margin:0 auto!important;background:transparent!important;overflow-y:visible!important;color:var(--ink)!important;position:relative!important;z-index:2!important}
      .header-beranda{background:transparent!important;border:0!important;box-shadow:none!important;padding:8px 0 0!important;margin:0 0 16px!important;color:var(--ink)!important;text-shadow:none!important;gap:14px!important}.profile-section{position:relative;padding-right:56px!important}.profile-section::before{content:'Selamat datang';display:block;font-size:11px;color:var(--muted);font-weight:650;margin-bottom:2px}.profile-section::after{content:'♻';position:absolute;right:0;top:0;width:44px;height:44px;border-radius:15px;background:#fff;border:1px solid var(--line);display:flex;align-items:center;justify-content:center;color:var(--green);font-size:24px;box-shadow:0 7px 18px rgba(23,111,84,.08)}.profile-section h2{margin:0!important;font-size:23px!important;color:var(--ink)!important}.profile-section p{margin:4px 0 0!important;color:#658077!important;font-size:11px!important}
      .rekap-card{position:relative!important;overflow:hidden!important;min-height:188px!important;width:100%!important;background:linear-gradient(145deg,#bff3e5,#a8ead7)!important;border:0!important;border-radius:28px!important;padding:24px 145px 24px 22px!important;color:var(--ink)!important;display:block!important;box-shadow:0 16px 30px rgba(21,130,98,.10)!important}.rekap-card::before{content:'Koleksi Sampah';display:block;font-size:13px;font-weight:800;color:#2b6657;margin-bottom:24px}.rekap-card::after{content:'';position:absolute;right:-26px;bottom:-44px;width:170px;height:170px;border-radius:50%;background:rgba(255,255,255,.23)}.rekap-item{display:block!important;text-align:left!important;position:relative!important;z-index:3!important}.rekap-item:first-child .rekap-label{display:none!important}.rekap-item:first-child .rekap-value{font-size:39px!important;line-height:1!important;font-weight:900!important;letter-spacing:-.04em!important;color:#102f27!important}.rekap-item:first-child .rekap-value::after{content:' terkumpul';display:block;font-size:11px;font-weight:650;letter-spacing:0;color:#4c776b;margin-top:8px}.rekap-divider{display:none!important}.rekap-item:nth-of-type(2){margin-top:18px!important}.rekap-item:nth-of-type(2) .rekap-label{font-size:9px!important;color:#558074!important}.rekap-item:nth-of-type(2) .rekap-value{font-size:12px!important;color:#315e52!important;font-weight:800!important}.clean-bin-art{position:absolute;right:18px;top:44px;width:126px;height:112px;z-index:2;filter:drop-shadow(0 10px 12px rgba(8,116,88,.15))}.clean-bin-art svg{width:100%;height:100%;display:block}
      #btn-savings-book{display:none!important}.search-beranda{width:100%!important;margin:0 0 18px!important;padding:13px 16px!important;border:1px solid var(--line)!important;border-radius:18px!important;background:#fff!important;color:var(--ink)!important;box-shadow:0 5px 16px rgba(33,104,83,.05)!important}.clean-section-title{display:flex;align-items:center;justify-content:space-between;margin:2px 2px 12px;font-weight:900;color:var(--ink)}.clean-section-title strong{font-size:17px}.clean-section-title span{font-size:10px;color:#678078;font-weight:750}
      .category-grid{display:grid!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:10px!important;padding:0 0 18px!important}.cat-card{min-width:0!important;min-height:126px!important;padding:14px 7px 12px!important;border:1px solid var(--line)!important;border-radius:21px!important;background:#f8fffd!important;box-shadow:0 7px 18px rgba(31,108,84,.055)!important;text-align:center!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:8px!important}.cat-card:active{transform:scale(.97)!important;background:#edf9f5!important}.cat-icon{width:54px;height:54px;border-radius:18px;background:#dff6ef;display:flex!important;align-items:center!important;justify-content:center!important;font-size:28px!important;margin:0!important}.cat-title{font-size:11px!important;line-height:1.22!important;color:#24483e!important;font-weight:800!important}
      .modal-overlay{background:rgba(20,49,40,.42)!important;backdrop-filter:blur(5px)!important}.modal-content{background:#f5fcf9!important;border-radius:28px 28px 0 0!important;padding:18px!important;box-shadow:0 -16px 50px rgba(12,69,51,.18)!important}.modal-header{border-bottom:1px solid var(--line)!important;padding-bottom:12px!important}.modal-title{color:var(--ink)!important;font-size:17px!important}.modal-close{background:#e1f4ed!important;color:#356357!important;border-radius:50%!important;width:32px!important;height:32px!important}.subcat-grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:10px!important}.subcat-card{background:#fff!important;border:1px solid var(--line)!important;border-radius:18px!important;box-shadow:0 5px 14px rgba(31,108,84,.05)!important}
      @media(min-width:700px){#halaman-beranda{margin-top:18px!important;border-radius:32px;background:#ecfaf6!important;box-shadow:0 18px 55px rgba(20,80,62,.08)!important}}
    `;document.head.appendChild(s);
  }

  function addHeroArt(){
    const card=document.querySelector('.rekap-card');if(!card||card.querySelector('.clean-bin-art'))return;
    const art=document.createElement('div');art.className='clean-bin-art';art.innerHTML=`<svg viewBox="0 0 160 132" fill="none" xmlns="http://www.w3.org/2000/svg"><ellipse cx="82" cy="120" rx="61" ry="8" fill="#6ACDB2" opacity=".22"/><rect x="18" y="48" width="38" height="66" rx="9" fill="#66D1B5"/><rect x="23" y="40" width="28" height="12" rx="6" fill="#229E7A"/><rect x="61" y="29" width="49" height="85" rx="12" fill="#15B989"/><rect x="69" y="19" width="34" height="14" rx="7" fill="#087458"/><rect x="115" y="48" width="28" height="66" rx="8" fill="#66D1B5"/><rect x="119" y="41" width="21" height="11" rx="5" fill="#229E7A"/><circle cx="86" cy="72" r="19" fill="#DDF8EF"/><path d="M83 58l7 5-4 7m11 4-6 8-8-2m-7-1-1-9 6-6" stroke="#16B98A" stroke-width="5" stroke-linecap="round" stroke-linejoin="round"/><path d="M27 68h20M27 79h20M27 90h20M121 69h15M121 80h15M121 91h15" stroke="#DDF8EF" stroke-width="4" stroke-linecap="round"/><circle cx="26" cy="115" r="5" fill="#087458"/><circle cx="49" cy="115" r="5" fill="#087458"/><circle cx="69" cy="115" r="6" fill="#087458"/><circle cx="100" cy="115" r="6" fill="#087458"/><circle cx="121" cy="115" r="5" fill="#087458"/><circle cx="138" cy="115" r="5" fill="#087458"/></svg>`;card.appendChild(art);
  }

  function addSectionTitle(){const grid=$('category-grid');if(!grid||$('clean-section-title'))return;const t=document.createElement('div');t.id='clean-section-title';t.className='clean-section-title';t.innerHTML='<strong>Kategori Sampah</strong><span>Pilih untuk mulai menimbang ›</span>';grid.parentNode.insertBefore(t,grid);}
  function install(){installStyle();addHeroArt();addSectionTitle();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
  window.addEventListener('load',()=>setTimeout(install,30),{once:true});
})();
